image: docker:latest

services:
- docker:dind

build:
  stage: build
  script:
    - docker login -u elerion -p Hjz7mLIG
    - docker build -t elerion/guest-book-server .
    - docker push elerion/guest-book-server
